ansible_become_pass: ENC[AES256_GCM,data:MxsUyl5kHrM=,iv:aB747AXdOXOCV6kOhqFYIgZHO31EeKubVqSBduDQ7Ns=,tag:yHn3x9s9qAjAEnT9sQmgCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tvslap8yyzxhf4364sp0rlrmmyd8ky2gxrttka67c0tpvgrqk9gsfpke5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZE5SZTJKSml1ZWtOVHhz
            RlFiNmlvNUpUNGU5MzdnWXY0OGxmUTg5bjA4CjJXcXYyS2t4UlZCVS92T2pZMnZI
            VlNlelZib0JVTTlubnAva0duTVcvRzAKLS0tIDVuVnN3RTAyYWQ1SUxJaVpVSlg1
            L0t1dWlkdTRVaVltOGFrTjY5cS8xSlUKOT081DDXSFS3UjziU3RA7Ozf2KKfs8Ul
            bceb6veTEovnCcibdPxyRDmj2OoBRkmXtAzri2PJ80YUann4r/b9GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-01T00:18:33Z"
    mac: ENC[AES256_GCM,data:PhTe4/HLEimJN1R0rTNh1979dAqJ9hg86hdzCEPCc7UkbWU2FsuAQhxuBwP/YeH98Dg8sTMxqNRMgLJ8Dve0HGpq5iUjSMDZ/sG0HIsIDS8ua0vPbf8tr/Ck5RUJA+7BkXcntWVl6By55qfHMrE9qyGGHsa7kTfPevmTN2MuZ+Q=,iv:bGpycXJy5aAkFOIz8XR3skIm8ws78xnTStgGoPDIE74=,tag:g/GocPVX/V/ybwO7Db29uw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
