apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:fIT2UfI=,iv:Z0oG22zlUqD51CZcMlM7GDgDbHJr47OFyjnCO2YvC7E=,tag:QAqHP+ljD1EvrsxZGsJ7BQ==,type:str]
    admin-user: ENC[AES256_GCM,data:toVzbV8=,iv:3XFi70s5vTjXXIfKLCzIh1zPpICYKfaS9IvAGopBC1E=,tag:/grqoldCTU3jsPzdgXMqMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tvslap8yyzxhf4364sp0rlrmmyd8ky2gxrttka67c0tpvgrqk9gsfpke5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUmNTM0NDUzVuaGxBZTky
            SDBzTG53ZldFTzBNdHoxTy9MeDlyTTgvOGhJCkMvTlZ2cVRFSVYzWXRzU3lCdEE2
            MlR4M1JSbHBnYm9hTDVUTHUrZTlaVEEKLS0tIDgzMUlGTHBiTk5ScXVEMHpFcU1M
            QnRvdmZqb0JnTkxRT2xWRExJRlY4MGcKPuLHjUmXDQyKCqj4JSH3wKV+YdVsnXhJ
            D+clNauRRwsd8j8ZSJUDSqp1JUZaxtSwgdkf1ItRBzybhL2+WUIr+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T15:53:21Z"
    mac: ENC[AES256_GCM,data:SVnhkSYXx/rbWRiZuuNdDo0wMYmY1bcMT+9mmMkCHCQ9t/oEurrBXsPxjC1k0RVE2uXkb4jm9sBhcJeasGzUTxB4xwPwGp257psQN7+Dl46YBdm1NFED7T7tj08F60OHsBwvy6MjTAeADE8efbBSe1lUFmEK+qWuhWJhDRTvTd8=,iv:XXYK90pDIOwiXrSr2H+Bu+3jk00reR31RJrQQkNihjo=,tag:qvzTshsG6yex2FnJ2F6I8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
