apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:hfTW38hRO6MKJyWW6KyQQwNx8SWOkpK+x1hIhP9T18RohYZRB9MzSA==,iv:JhvGXUvktZQh2GJphTnS+iljgzicxdX2EH5f7BNiQR8=,tag:OjlS/iyRChOZ9cQ+Bdr0hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tvslap8yyzxhf4364sp0rlrmmyd8ky2gxrttka67c0tpvgrqk9gsfpke5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSkFsSUNKZW9tQkgramxJ
            aEU4ZzE2M1RsZDZTRWV4K3JGNFhkWCtmdkMwCldjNVpuZm11azR1RlN6aFdaWXdt
            RE5lRlF4a2FlMEdvUHdCWlNub1NTd1kKLS0tIFM4NTdZdjg2QzZ5OEZ1bnJqOC85
            OU1RbWJHU0l0OVJFMXM0T04yWkVxQ1kKAiTVfXzNKX5ogDWQpPbZuxC1Bv543COg
            cl1/wpwaz9mmKsrcQjgilPyWqQZa3929ex2iw3jovXSJe84ULW43Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T15:53:16Z"
    mac: ENC[AES256_GCM,data:SczIFlgJgWPkB+k/p3CQbMiF9fnQnU9nZHWc0slOxJ8hXC68zC0uMrzdOAxkFUWGM9AxcC9IFoyERBV8tbZIIncyiQdvqM0KUi/QAfSSfVlBVi6UUmJ37Kx1sSJrqnWYBXsLH+BAHX2WBPwSG3IRkit9xSAAFxZFfWrGNVnUjAk=,iv:T1hxOuxWzlfuczIDmUTVzGhggR8E+feNMLwQLLghDiU=,tag:4SLv168uWJqnxlJpg2kOiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
