apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_SONARR__API_KEY: ENC[AES256_GCM,data:wVlTAwe0BE62rM7t1MouTyBv4DsxWdzbsYO+ZBxnTbk=,iv:0GtuCfLAzjXlDLyeEuD+5URsmUbmicygnfA09QqSGE4=,tag:AaeyUiQAuJ4UhxEyb0bHtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tvslap8yyzxhf4364sp0rlrmmyd8ky2gxrttka67c0tpvgrqk9gsfpke5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY01TOS93V3hkdzkxSjRO
            ak5zcXFmekI4TnZNTWVlRE5zSlY3bngrR2pjCnpDdEJWcmxqNlQrRksrVkhoUmJ2
            U2h6SUxQS0REOW56ZFlEcmNsUkk3TGcKLS0tIGtDS2NZVmJMbmNwa1Vscy9abHNR
            Sk9vOHgvYWRmYnVJUnlWWjRaU0pFaE0K3rMlb4pEx951FKDyE6FtBbstuRfCQh8r
            PqMTByT3pOTig00l/SORT5yRnDg/4RWvdoVa5WUcPEENa3HPMAaMTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T18:13:59Z"
    mac: ENC[AES256_GCM,data:HK8Nfz9AYcFj1BF0xS2RVQqGPho3vpAiy0swpn9cqm91Dvo3kw/pbf5tdBZPYEtYIWsUebN1WWxoTGpVlk7kCdrz+bm+dMQz/BAKYFKWpJdZA9WxBLYxT7DGIqXY34XD9mKtzAippQbML7CniExt+6es9wSZVOwSZGrZffrYmss=,iv:pja2DcAm/CDzo5wH8zIbtZa0WiD0TJ4BpOM1HK5Mk1s=,tag:gNuB2Cbz9CMc9wwfRcwRng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
