apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Kma6MNoG6tUR5ILiaAIFkNlIp52kOrHlU1Ok9TPTU0g+89fe,iv:+99W3Kze96yWSb4UbkSUsjuPyzNK/RKQgFxzj2YYHG0=,tag:XRv1MP0Am7WRgRhOzOLBwg==,type:str]
    credentials.json: ENC[AES256_GCM,data:TetQcDMF+o5ooLecv4Qn9guS+AXDS1WWpFZqaE9XiGVyuVuIgAPK19HDFUfqf70YfmYIzjOaRukF3V0UvqW8xpw6zGOmfByJcjlXIMlW4kJd5zpRDpTvCe2ZfgJWbY9kgN67/+g9hQC39wwZGDKF2tH34y4oI72fXV+GK9G6b+at+89fuzuKhX/Jtz4g+ldSnDGkkY6wFXT+XENvfUVqCAKgVb2FKCQ1tPT/khF3Yg==,iv:fEJetnL/CmxNyYmDvVVUST5RXBJ81GroYTsi0vkLMq4=,tag:Zk4lE6I49cQc/Bowc4a+SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tvslap8yyzxhf4364sp0rlrmmyd8ky2gxrttka67c0tpvgrqk9gsfpke5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZWJiUmo2V0R6YWtJYmRJ
            OGNMU1FXK2k4Y3pQdVpjWi9PREhJb0ExMnljCnN5emljTEx3VkVlTFo5SWo3b082
            YlFQZXlxMFlvdDQvTVBVZUhleDZBREkKLS0tIGgrcGt4cWtjeTBLdGdLcmUwM1BX
            SFB3NmFzVWgxQ3JnVTdGSit1NVkvaDQKD4X3gHoFlHYZCXBAyTXS2W+VyKqj3cER
            oHG+4PAYF1XWyuECd6nMmCBkucHrLVpPIM2ndqNbkEZsI7DItItk5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-01T00:19:05Z"
    mac: ENC[AES256_GCM,data:ScHOVhlC47veLw5o3IOB6dwFAbYWLUKBfHcDh3V7YnZjZXATE7qW0c1KApnHQyT86G4eS1tqC19P5doSfdjd06E1waIKCkKhtfwSDWD0OHc3GkjGb1Q114ZGTerkbBzHaPE/c9ww048kp621yGNooRa9fI9T5jWiRp+zxxULYXc=,iv:4ckMAjdq2C7XhoBsVsNA4KKCwwwP4Z6yikJeQ6qoLa4=,tag:3wYkNnNFTYyMp0Tub0ZgYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
