apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:52RqcLj8ZqxFSLfKV8nlLpPzgYvVUjiOXNpxCuBxmw1f9NnB,iv:W87S0CPeFf6U5p139qNRFUe8woApx8wK30ETvg1QrMk=,tag:VnxplTNilIkwHJUNOPg2Zw==,type:str]
    credentials.json: ENC[AES256_GCM,data:L/ey5HMMGSk5MjQquUGm/Wrz3RAXHJ8SnPKJk63kH6mbS8Crh8LQr2Hh/1TYEyMBoinTUjnpBq73VjLnkETkgPHL+Fr+b5P35PnbplNLLKWDZlncMWzm6kydMlJ9zKuet6/KoPKXZhd83P/amLVGAC9s/+a8cmjiFX4b+Z0qwEBAP8114GXEY/3OFngtGY5oDznGn8sMqpmfaJHTm8Kk66efN9bTrrqUxZQkdOWvtA==,iv:DkLMHddytrXZQ3GVFaiZCNjgSu2LVprS2a1kzeskHvo=,tag:LDaruBLehXg8adeTlET/xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tvslap8yyzxhf4364sp0rlrmmyd8ky2gxrttka67c0tpvgrqk9gsfpke5p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK0RSNWRrUVlybjdDL3lm
            RlVWdWhuZ3RGYU1HVEtadVE1K0VValIwbURNClFMZ3FEUGxOU0dSMmdpMUdYZDJp
            ZlhVYUxGaVoxM1dxWlJndzBraVJ2Q0kKLS0tIGVZMjFjZXQvd2VCTWlOVE5ScGFH
            SjAzTWpNbXd6RzdXTGxjQnpMOWdFSVUK51/uCvQVOcV7uQC7VPHpeZHQPXRhzdkS
            lu6qkFbUMrXH5whJul8tBWM2R8GKLqhFALN64ZGwLmbAjl6GHwq6zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T15:53:16Z"
    mac: ENC[AES256_GCM,data:dULIAFfmLYql2HoR2KhpHZszVSf8sATQvoKNRODsnO5+WOWCKy/ZAfSdK/SbacrbOaZpkGTNsJZf+hVufzU1NtanVKcpIh2kyPwa0XpylKYv2lQnUNzPwavhzDNudzM+I2OK4Jt+vPMJfWAbj1gxz9fZQUZKBmqCFB7UoFHuMCc=,iv:GOh4En/zNze/uzBW9iCM3n8qNvj/iylirQWeKj5+AoI=,tag:MZCknIaNMCIcxZdeDIi3MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
